start-at-login = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
accordion-padding = 30

[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'

ctrl-alt-1 = 'move-node-to-workspace 1'
ctrl-alt-2 = 'move-node-to-workspace 2'
ctrl-alt-3 = 'move-node-to-workspace 3'
ctrl-alt-4 = 'move-node-to-workspace 4'
ctrl-alt-5 = 'move-node-to-workspace 5'
ctrl-alt-6 = 'move-node-to-workspace 6'
ctrl-alt-7 = 'move-node-to-workspace 7'
ctrl-alt-8 = 'move-node-to-workspace 8'
ctrl-alt-9 = 'move-node-to-workspace 9'

alt-f = 'fullscreen'
alt-shift-space = 'layout floating tiling'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-tab = 'workspace-back-and-forth'
alt-shift-c = 'reload-config'
alt-r = 'mode resize'

ctrl-alt-q = 'mode tens'
ctrl-alt-w = 'mode twenties'
ctrl-q = 'mode goto-tens'
ctrl-w = 'mode goto-twenties'

[mode.tens.binding]
0 = ['move-node-to-workspace 10', 'mode main']
1 = ['move-node-to-workspace 11', 'mode main']
2 = ['move-node-to-workspace 12', 'mode main']
3 = ['move-node-to-workspace 13', 'mode main']
4 = ['move-node-to-workspace 14', 'mode main']
5 = ['move-node-to-workspace 15', 'mode main']
6 = ['move-node-to-workspace 16', 'mode main']
7 = ['move-node-to-workspace 17', 'mode main']
8 = ['move-node-to-workspace 18', 'mode main']
9 = ['move-node-to-workspace 19', 'mode main']
esc = 'mode main'

[mode.twenties.binding]
0 = ['move-node-to-workspace 20', 'mode main']
1 = ['move-node-to-workspace 21', 'mode main']
2 = ['move-node-to-workspace 22', 'mode main']
3 = ['move-node-to-workspace 23', 'mode main']
4 = ['move-node-to-workspace 24', 'mode main']
5 = ['move-node-to-workspace 25', 'mode main']
6 = ['move-node-to-workspace 26', 'mode main']
7 = ['move-node-to-workspace 27', 'mode main']
8 = ['move-node-to-workspace 28', 'mode main']
9 = ['move-node-to-workspace 29', 'mode main']
esc = 'mode main'

[mode.goto-tens.binding]
0 = ['workspace 10', 'mode main']
1 = ['workspace 11', 'mode main']
2 = ['workspace 12', 'mode main']
3 = ['workspace 13', 'mode main']
4 = ['workspace 14', 'mode main']
5 = ['workspace 15', 'mode main']
6 = ['workspace 16', 'mode main']
7 = ['workspace 17', 'mode main']
8 = ['workspace 18', 'mode main']
9 = ['workspace 19', 'mode main']
esc = 'mode main'

[mode.goto-twenties.binding]
0 = ['workspace 20', 'mode main']
1 = ['workspace 21', 'mode main']
2 = ['workspace 22', 'mode main']
3 = ['workspace 23', 'mode main']
4 = ['workspace 24', 'mode main']
5 = ['workspace 25', 'mode main']
6 = ['workspace 26', 'mode main']
7 = ['workspace 27', 'mode main']
8 = ['workspace 28', 'mode main']
9 = ['workspace 29', 'mode main']
esc = 'mode main'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
minus = 'resize smart -50'
equal = 'resize smart +50'
esc = 'mode main'
